[tool.poetry]
name = "repl_python3_Mastermind"
version = "0.1.0"
description = ""
authors = ["mastermind2000 <<>>"]

[tool.poetry.dependencies]
python = "^3.8"
discord = "^1.7.3"
python-dotenv = "^0.19.1"
youtube_dl = "^2021.6.6"
pafy = "^0.5.5"
PyNaCl = "^1.4.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
